name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Make build script executable
      - name: Correct file permissions
        run: chmod +x ./build.sh

        # Run our build script to build and deploy
      - name: Build and deploy
        env:
          SCW_USER: ${{ secrets.SCW_USER }}
          SCW_SECRET: ${{ secrets.SCW_SECRET }}
        run: ./build.sh

      # Have K8S pull latest images for dev pods
      #- name: Trigger dev deploy
      #  uses: davi020/kubernetes-action@master
      #  env:
      #    KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      #  with:
      #    args: delete -n discal pods -l profile=dev,app=discal,module=web
